[build]
  base = "widget-next"
  command = "yarn install --frozen-lockfile && yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
